const state = { playerCount: 0, players: [], order: [], parentIndex: 0, card: null, official: [], words: [], parentWord: "", answers: {}, answerIndex: 0, timer: null, usedCards: new Set(), round: 0 };
const screens = document.querySelectorAll("[data-screen]");
const show = (name) => screens.forEach((s) => s.classList.toggle("is-hidden", s.dataset.screen !== name));
const esc = (v) => String(v).replace(/[&<>'"]/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const shuffle = (a) => { const b = [...a]; for (let i=b.length-1;i>0;i--) { const j=Math.floor(Math.random()*(i+1)); [b[i],b[j]]=[b[j],b[i]]; } return b; };
function handoff(player, next) { document.querySelector("#handoff-text").innerHTML = `あなたは<strong>${esc(player.name)}</strong>さんですか？<br>${next || ""}<br>${esc(player.name)}さんであれば「OK」を押してください。`; show("handoff"); state.handoffNext = next; }
function chooseCard() { const cards = state.cards || []; const available = cards.filter((c) => !state.usedCards.has(c.id)); if (!available.length) state.usedCards.clear(); const pool = available.length ? available : cards; state.card = pool[Math.floor(Math.random()*pool.length)]; state.usedCards.add(state.card.id); state.official = shuffle(state.card.officialWords).slice(0,3); }
async function loadCards() { try { const r=await fetch("cards/cards.json"); if (!r.ok) throw Error(); state.cards=await r.json(); } catch { state.cards=[{id:1,image:"",officialWords:["りんご","鴨","奇妙な組み合わせ"]}]; } }
for (let n=2;n<=10;n++) { const b=document.createElement("button"); b.className="count-button"; b.textContent=`${n}人`; b.onclick=()=>{state.playerCount=n; document.querySelector("#name-description").textContent=`${n}人分の名前を入力してください。`; const f=document.querySelector("#name-fields"); f.replaceChildren(); for(let i=0;i<n;i++){const l=document.createElement("label");l.className="field-label";l.innerHTML=`プレイヤー${i+1}<input name="p${i}" maxlength="20" autocomplete="off" placeholder="名前を入力" />`;f.append(l)} show("player-names");f.querySelector("input").focus()}; document.querySelector("#player-counts").append(b); }
document.querySelector("#back-button").onclick=()=>show("player-count");
document.querySelector("#player-form").onsubmit=(e)=>{e.preventDefault();const names=[...new FormData(e.target).values()].map(v=>String(v).trim()), err=document.querySelector("#form-error");if(names.some(n=>!n)){err.textContent="すべてのプレイヤー名を入力してください。";return}if(new Set(names).size!==names.length){err.textContent="プレイヤー名は重複しないようにしてください。";return}state.players=names.map((name,i)=>({id:i,name,score:0})); document.querySelector("#player-list").innerHTML=state.players.map(p=>`<div class="player-item"><span>${esc(p.name)}</span><span>0ポイント</span></div>`).join("");show("ready")};
document.querySelector("#start-button").onclick=async()=>{await loadCards();state.order=shuffle(state.players.map((_,i)=>i));state.parentIndex=0;startRound()};
function startRound(){state.round++;chooseCard();const p=state.players[state.order[state.parentIndex]];document.querySelector("#round-label").textContent=`ROUND ${state.round}`;document.querySelector("#round-title").textContent=`親は${p.name}さんです`;document.querySelector("#card-area").innerHTML=state.card.image?`<img src="${esc(state.card.image)}" alt="お題カード">`:`<div class="missing-card">カード画像</div>`;show("round")}
document.querySelector("#round-start-button").onclick=()=>{const p=state.players[state.order[state.parentIndex]];handoff(p,"親ワードを入力してください。")};
document.querySelector("#handoff-button").onclick=()=>{if(state.handoffNext?.includes("親ワード")){document.querySelector("#official-preview").innerHTML=state.official.map(w=>`<div class="word official">${esc(w)}</div>`).join("");document.querySelector("#parent-word").value="";show("parent-input")}else if(state.handoffNext?.includes("回答")){startAnswer()}else show("round")};
document.querySelector("#parent-submit").onclick=()=>{const v=document.querySelector("#parent-word").value.trim(),e=document.querySelector("#parent-error");if(!v){e.textContent="親ワードを入力してください。";return}state.parentWord=v;state.words=shuffle([...state.official,v]);document.querySelector("#public-words").innerHTML=state.words.map(w=>`<div class="word">${esc(w)}</div>`).join("");show("public");startTimer()};
function startTimer(){let left=120;const el=document.querySelector("#timer");clearInterval(state.timer);const tick=()=>{el.textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,"0")}`;if(left--<=0){clearInterval(state.timer);startAnswer()}};tick();state.timer=setInterval(tick,1000)}
document.querySelector("#discussion-end").onclick=()=>startAnswer();
function startAnswer(){clearInterval(state.timer);state.answers={};state.answerIndex=0;askAnswer()}
function askAnswer(){const children=state.players.filter((_,i)=>i!==state.order[state.parentIndex]);if(state.answerIndex>=children.length){showResults();return}const p=children[state.answerIndex];handoff(p,"回答を選択してください。");document.querySelector("#handoff-button").onclick=()=>{document.querySelector("#answer-title").textContent=`${p.name}さんの回答`;document.querySelector("#answer-description").textContent="親ワードだと思う候補を1つ選んでください。";document.querySelector("#answer-words").innerHTML=state.words.map((w,i)=>`<button class="word word-button" data-word="${esc(w)}">${esc(w)}</button>`).join("");document.querySelectorAll(".word-button").forEach(b=>b.onclick=()=>{state.answers[p.id]=b.dataset.word;state.answerIndex++;document.querySelector("#answer-next").textContent="回答を確定";document.querySelector("#answer-next").onclick=askAnswer;show("answer")});show("answer")}}
function showResults(){document.querySelector("#answer-summary").innerHTML=state.players.filter((_,i)=>i!==state.order[state.parentIndex]).map(p=>`<div class="player-item"><span>${esc(p.name)}さん</span><span>${esc(state.answers[p.id])}</span></div>`).join("");show("result")}
document.querySelector("#reveal-button").onclick=()=>{const children=state.players.filter((_,i)=>i!==state.order[state.parentIndex]),correct=children.filter(p=>state.answers[p.id]===state.parentWord),parent=state.players[state.order[state.parentIndex]];if(correct.length===0)parent.score++;else if(correct.length===children.length){parent.score--;children.forEach(p=>p.score++)}else correct.forEach(p=>p.score++);const winners=state.players.filter(p=>p.score>=5);document.querySelector("#score-title").textContent=winners.length?`勝利：${winners.map(p=>esc(p.name)).join("、")}`:(correct.length===0?"全員不正解":correct.length===children.length?"全員正解":"一部の子が正解");document.querySelector("#score-list").innerHTML=`<div class="word official">正解：${esc(state.parentWord)}</div>`+children.map(p=>`<div class="player-item"><span>${esc(p.name)}さん</span><span>${esc(state.answers[p.id])}${state.answers[p.id]===state.parentWord?"（正解）":"（不正解）"}</span></div>`).join("")+`<h2>得点</h2>`+state.players.map(p=>`<div class="player-item"><span>${esc(p.name)}</span><span>${p.score}ポイント</span></div>`).join("");document.querySelector("#next-round").textContent=winners.length?"続けて遊ぶ":"次のラウンドへ";show("scores")};
document.querySelector("#next-round").onclick=()=>{state.parentIndex=(state.parentIndex+1)%state.order.length;startRound()};
function stopGame(){clearInterval(state.timer);if(confirm("ゲームを中断して最初に戻りますか？")){location.reload()}};
["quit-button","public-quit","score-quit"].forEach(id=>document.querySelector(`#${id}`).onclick=stopGame);
