const state = { playerCount: 0, players: [], order: [], parentIndex: 0, card: null, official: [], words: [], parentWord: "", answers: {}, answerIndex: 0, timer: null, usedCards: new Set(), round: 0 };
const screens = document.querySelectorAll("[data-screen]");
const show = (name) => screens.forEach((s) => s.classList.toggle("is-hidden", s.dataset.screen !== name));
const esc = (v) => String(v).replace(/[&<>'"]/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const shuffle = (a) => { const b = [...a]; for (let i=b.length-1;i>0;i--) { const j=Math.floor(Math.random()*(i+1)); [b[i],b[j]]=[b[j],b[i]]; } return b; };
function handoff(player, next) { document.querySelector("#handoff-text").innerHTML = `ããªãã¯<strong>${esc(player.name)}</strong>ããã§ããï¼<br>${next || ""}<br>${esc(player.name)}ããã§ããã°ãOKããæ¼ãã¦ãã ããã`; show("handoff"); state.handoffNext = next; }
function chooseCard() { const cards = state.cards || []; const available = cards.filter((c) => !state.usedCards.has(c.id)); if (!available.length) state.usedCards.clear(); const pool = available.length ? available : cards; state.card = pool[Math.floor(Math.random()*pool.length)]; state.usedCards.add(state.card.id); state.official = shuffle(state.card.officialWords).slice(0,3); }
async function loadCards() { try { const r=await fetch("cards/cards.json"); if (!r.ok) throw Error(); state.cards=await r.json(); } catch { state.cards=[{id:1,image:"",officialWords:["ããã","é´¨","å¥å¦ãªçµã¿åãã"]}]; } }
for (let n=2;n<=10;n++) { const b=document.createElement("button"); b.className="count-button"; b.textContent=`${n}äºº`; b.onclick=()=>{state.playerCount=n; document.querySelector("#name-description").textContent=`${n}äººåã®ååãå¥åãã¦ãã ããã`; const f=document.querySelector("#name-fields"); f.replaceChildren(); for(let i=0;i<n;i++){const l=document.createElement("label");l.className="field-label";l.innerHTML=`ãã¬ã¤ã¤ã¼${i+1}<input name="p${i}" maxlength="20" autocomplete="off" placeholder="ååãå¥å" />`;f.append(l)} show("player-names");f.querySelector("input").focus()}; document.querySelector("#player-counts").append(b); }
document.querySelector("#back-button").onclick=()=>show("player-count");
document.querySelector("#player-form").onsubmit=(e)=>{e.preventDefault();const names=[...new FormData(e.target).values()].map(v=>String(v).trim()), err=document.querySelector("#form-error");if(names.some(n=>!n)){err.textContent="ãã¹ã¦ã®ãã¬ã¤ã¤ã¼åãå¥åãã¦ãã ããã";return}if(new Set(names).size!==names.length){err.textContent="ãã¬ã¤ã¤ã¼åã¯éè¤ããªãããã«ãã¦ãã ããã";return}state.players=names.map((name,i)=>({id:i,name,score:0})); document.querySelector("#player-list").innerHTML=state.players.map(p=>`<div class="player-item"><span>${esc(p.name)}</span><span>0ãã¤ã³ã</span></div>`).join("");show("ready")};
document.querySelector("#start-button").onclick=async()=>{await loadCards();state.order=shuffle(state.players.map((_,i)=>i));state.parentIndex=0;startRound()};
function startRound(){state.round++;chooseCard();const p=state.players[state.order[state.parentIndex]];document.querySelector("#round-label").textContent=`ROUND ${state.round}`;document.querySelector("#round-title").textContent=`è¦ªã¯${p.name}ããã§ã`;document.querySelector("#card-area").innerHTML=state.card.image?`<img src="${esc(state.card.image)}" alt="ãé¡ã«ã¼ã">`:`<div class="missing-card">ã«ã¼ãç»å</div>`;show("round")}
document.querySelector("#round-start-button").onclick=()=>{const p=state.players[state.order[state.parentIndex]];handoff(p,"è¦ªã¯ã¼ããå¥åãã¦ãã ããã")};
document.querySelector("#handoff-button").onclick=()=>{if(state.handoffNext?.includes("è¦ªã¯ã¼ã")){document.querySelector("#official-preview").innerHTML=state.official.map(w=>`<div class="word official">${esc(w)}</div>`).join("");document.querySelector("#parent-word").value="";show("parent-input")}else if(state.handoffNext?.includes("åç­")){startAnswer()}else show("round")};
document.querySelector("#parent-submit").onclick=()=>{const v=document.querySelector("#parent-word").value.trim(),e=document.querySelector("#parent-error");if(!v){e.textContent="è¦ªã¯ã¼ããå¥åãã¦ãã ããã";return}state.parentWord=v;state.words=shuffle([...state.official,v]);document.querySelector("#public-words").innerHTML=state.words.map(w=>`<div class="word">${esc(w)}</div>`).join("");show("public");startTimer()};
function startTimer(){let left=120;const el=document.querySelector("#timer");clearInterval(state.timer);const tick=()=>{el.textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,"0")}`;if(left--<=0){clearInterval(state.timer);startAnswer()}};tick();state.timer=setInterval(tick,1000)}
document.querySelector("#discussion-end").onclick=()=>startAnswer();
function startAnswer(){clearInterval(state.timer);state.answers={};state.answerIndex=0;askAnswer()}
function askAnswer(){const children=state.players.filter((_,i)=>i!==state.order[state.parentIndex]);if(state.answerIndex>=children.length){showResults();return}const p=children[state.answerIndex];handoff(p,"åç­ãé¸æãã¦ãã ããã");document.querySelector("#handoff-button").onclick=()=>{document.querySelector("#answer-title").textContent=`${p.name}ããã®åç­`;document.querySelector("#answer-description").textContent="è¦ªã¯ã¼ãã ã¨æãåè£ã1ã¤é¸ãã§ãã ããã";document.querySelector("#answer-words").innerHTML=state.words.map((w,i)=>`<button class="word word-button" data-word="${esc(w)}">${esc(w)}</button>`).join("");document.querySelectorAll(".word-button").forEach(b=>b.onclick=()=>{state.answers[p.id]=b.dataset.word;state.answerIndex++;document.querySelector("#answer-next").textContent="åç­ãç¢ºå®";document.querySelector("#answer-next").onclick=askAnswer;show("answer")});show("answer")}}
function showResults(){document.querySelector("#answer-summary").innerHTML=state.players.filter((_,i)=>i!==state.order[state.parentIndex]).map(p=>`<div class="player-item"><span>${esc(p.name)}ãã</span><span>åç­æ¸ã¿</span></div>`).join("");show("result")}
document.querySelector("#reveal-button").onclick=()=>{const children=state.players.filter((_,i)=>i!==state.order[state.parentIndex]),correct=children.filter(p=>state.answers[p.id]===state.parentWord),parent=state.players[state.order[state.parentIndex]];if(correct.length===0)parent.score++;else if(correct.length===children.length){parent.score--;children.forEach(p=>p.score++)}else correct.forEach(p=>p.score++);const winners=state.players.filter(p=>p.score>=5);document.querySelector("#score-title").textContent=winners.length?`åå©ï¼${winners.map(p=>esc(p.name)).join("ã")}`:(correct.length===0?"å¨å¡ä¸æ­£è§£":correct.length===children.length?"å¨å¡æ­£è§£":"ä¸é¨ã®å­ãæ­£è§£");document.querySelector("#score-list").innerHTML=`<div class="word official">æ­£è§£ï¼${esc(state.parentWord)}</div>`+children.map(p=>`<div class="player-item"><span>${esc(p.name)}ãã</span><span>${esc(state.answers[p.id])}${state.answers[p.id]===state.parentWord?"ï¼æ­£è§£ï¼":"ï¼ä¸æ­£è§£ï¼"}</span></div>`).join("")+`<h2>å¾ç¹</h2>`+state.players.map(p=>`<div class="player-item"><span>${esc(p.name)}</span><span>${p.score}ãã¤ã³ã</span></div>`).join("");document.querySelector("#next-round").textContent=winners.length?"ç¶ãã¦éã¶":"æ¬¡ã®ã©ã¦ã³ãã¸";show("scores")};
document.querySelector("#next-round").onclick=()=>{state.parentIndex=(state.parentIndex+1)%state.order.length;startRound()};
function stopGame(){clearInterval(state.timer);if(confirm("ã²ã¼ã ãä¸­æ­ãã¦æåã«æ»ãã¾ããï¼")){location.reload()}};
["quit-button","public-quit","score-quit"].forEach(id=>document.querySelector(`#${id}`).onclick=stopGame);
