const PLAYER_STORAGE_KEY = "word-card-players";
const savedPlayers = (() => { try { const v=JSON.parse(localStorage.getItem(PLAYER_STORAGE_KEY)||"[]"); return Array.isArray(v)?v.map(String):[]; } catch { return []; } })();
const state = { playerCount:0, cardSet:"vol1", players:[], order:[], parentIndex:0, card:null, official:[], words:[], parentWord:"", answers:{}, answerIndex:0, answerLocked:false, selectedAnswer:"", timer:null, usedCards:new Set(), round:0, handoffNext:"" };
const screens=document.querySelectorAll("[data-screen]");
function show(name){
  screens.forEach(s=>s.classList.toggle("is-hidden",s.dataset.screen!==name));
  window.scrollTo(0,0);
  document.documentElement.scrollTop=0;
  document.body.scrollTop=0;
  requestAnimationFrame(()=>window.scrollTo(0,0));
}
const esc=v=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;};
function cardImagePath(image){return image?(image.startsWith("cards/")?image:`cards/${state.cardSet}/${image}`):"";}
function cardMarkup(card){const src=cardImagePath(card?.image);return src?`<img src="${esc(src)}" alt="お題カード" onerror="this.parentElement.innerHTML='<div class=&quot;missing-card&quot;>カード画像を読み込めませんでした</div>'">`:`<div class="missing-card">カード画像を読み込めません</div>`;}
function handoff(player,next){document.querySelector("#handoff-text").innerHTML=`全員イラストを確認してください。<br>確認できたら、${esc(player.name)}さんが「OK」を押して親ワード入力へ進んでください。`;document.querySelector("#handoff-card-area").innerHTML=cardMarkup(state.card);state.handoffNext=next;show("handoff");}
function chooseCard(){const cards=state.cards||[];let available=cards.filter(c=>!state.usedCards.has(c.id));if(!available.length){state.usedCards.clear();available=cards;}state.card=available[Math.floor(Math.random()*available.length)];state.usedCards.add(state.card.id);state.official=shuffle(state.card.officialWords).slice(0,3);}
async function loadCards(){try{const r=await fetch(`cards/${state.cardSet}/cards.json`);if(!r.ok)throw Error();const d=await r.json();if(!Array.isArray(d)||!d.length)throw Error();state.cards=d;}catch{state.cards=[{id:1,image:"",officialWords:["りんご","鴨","奇妙な組み合わせ"]}];}}
function renderOrder(){const list=document.querySelector("#player-list");if(!list)return;list.innerHTML=state.order.map((i,n)=>`<div class="player-item"><span>${n+1}. ${esc(state.players[i].name)}</span></div>`).join("");}
function showReady(){
  state.order=shuffle(state.players.map((_,i)=>i));
  state.parentIndex=0;
  show("ready");
  renderOrder();
  requestAnimationFrame(renderOrder);
}
for(let n=3;n<=6;n++){const b=document.createElement("button");b.className="count-button";b.textContent=`${n}人`;b.onclick=()=>{state.playerCount=n;document.querySelector("#name-description").textContent=`${n}人分の名前を入力してください。`;const f=document.querySelector("#name-fields");f.replaceChildren();for(let i=0;i<n;i++){const l=document.createElement("label");l.className="field-label";l.innerHTML=`プレイヤー${i+1}<input name="p${i}" maxlength="20" autocomplete="off" placeholder="名前を入力" />`;f.append(l);}if(savedPlayers.length===n)[...f.querySelectorAll("input")].forEach((x,i)=>x.value=savedPlayers[i]||"");show("player-names");f.querySelector("input").focus();};document.querySelector("#player-counts").append(b);}
document.querySelectorAll("[data-card-set]").forEach(button=>button.onclick=()=>{state.cardSet=button.dataset.cardSet;document.querySelectorAll("[data-card-set]").forEach(x=>x.classList.toggle("is-selected",x===button));});
document.querySelector("#title-start").onclick=()=>show("player-count");
document.querySelector("#howto-button").onclick=()=>show("howto");
document.querySelector("#howto-back").onclick=()=>show("title");
document.querySelector("#back-button").onclick=()=>show("player-count");
document.querySelector("#player-form").onsubmit=e=>{e.preventDefault();const names=[...new FormData(e.target).values()].map(v=>String(v).trim()),err=document.querySelector("#form-error");err.textContent="";if(names.some(n=>!n)){err.textContent="すべてのプレイヤー名を入力してください。";return;}if(new Set(names).size!==names.length){err.textContent="プレイヤー名は重複しないようにしてください。";return;}state.players=names.map((name,i)=>({id:i,name,score:0}));try{localStorage.setItem(PLAYER_STORAGE_KEY,JSON.stringify(names));}catch{}showReady();};
document.querySelector("#start-button").onclick=async()=>{await loadCards();startRound();};
function startRound(){state.round++;chooseCard();const p=state.players[state.order[state.parentIndex]];document.querySelectorAll("[data-round-title]").forEach(x=>x.textContent=`ROUND${state.round} ${x.dataset.roundTitle}`);document.querySelector("#round-title").textContent=`親：${p.name}`;document.querySelector("#round-card-message").textContent=`${p.name}さん、山札からカードを1枚引いてください。`;document.querySelector("#round-start-button").disabled=false;document.querySelector("#draw-card").textContent="カードを引く";show("round");}
document.querySelector("#round-start-button").onclick=()=>{document.querySelector("#round-start-button").disabled=true;document.querySelector("#draw-card").textContent="カードを引きました";document.querySelector("#handoff-card-area").innerHTML=cardMarkup(state.card);handoff(state.players[state.order[state.parentIndex]],"親ワード入力");};
document.querySelector("#handoff-button").onclick=()=>{document.querySelector("#parent-card-area").innerHTML=cardMarkup(state.card);document.querySelector("#official-preview").innerHTML=state.official.map(w=>`<div class="word official">${esc(w)}</div>`).join("");document.querySelector("#parent-word").value="";show("parent-input");};
document.querySelector("#parent-submit").onclick=()=>{const v=document.querySelector("#parent-word").value.trim(),e=document.querySelector("#parent-error");if(!v){e.textContent="親ワードを入力してください。";return;}e.textContent="";state.parentWord=v;state.words=shuffle([...state.official,v]);document.querySelector("#public-card-area").innerHTML=cardMarkup(state.card);show("word-open");};
document.querySelector("#word-open-button").onclick=()=>{const words=state.words.map(w=>`<div class="word">${esc(w)}</div>`).join("");document.querySelector("#discussion-open-card-area").innerHTML=cardMarkup(state.card);document.querySelector("#discussion-open-words").innerHTML=words;document.querySelector("#discussion-card-area").innerHTML=cardMarkup(state.card);document.querySelector("#public-words").innerHTML=words;document.querySelector("#timer").textContent="1:00";show("discussion-open");};
function startTimer(){let left=60;const el=document.querySelector("#timer");clearInterval(state.timer);const tick=()=>{el.textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,"0")}`;if(left--<=0){clearInterval(state.timer);startAnswer();}};tick();state.timer=setInterval(tick,1000);}
document.querySelector("#discussion-start").onclick=()=>{show("discussion");startTimer();};
document.querySelector("#discussion-end").onclick=startAnswer;
function startAnswer(){clearInterval(state.timer);state.answers={};state.answerIndex=0;state.answerLocked=false;askAnswer();}
function askAnswer(){const children=state.players.filter((_,i)=>i!==state.order[state.parentIndex]);if(state.answerIndex>=children.length){showResultOpen();return;}const answerIndex=state.answerIndex,p=children[answerIndex],submit=document.querySelector("#answer-submit");state.answerLocked=false;state.selectedAnswer="";document.querySelector("#answer-card-area").innerHTML=cardMarkup(state.card);document.querySelector("#answer-title").textContent=`${p.name}さんの回答`;document.querySelector("#answer-words").innerHTML=state.words.map(w=>`<button class="word word-button" data-word="${esc(w)}">${esc(w)}</button>`).join("");submit.disabled=true;document.querySelectorAll(".word-button").forEach(b=>b.onclick=()=>{if(state.answerLocked||state.answerIndex!==answerIndex)return;state.selectedAnswer=b.dataset.word;document.querySelectorAll(".word-button").forEach(button=>button.classList.toggle("is-selected",button===b));submit.disabled=false;});submit.onclick=()=>{if(state.answerLocked||state.answerIndex!==answerIndex||!state.selectedAnswer)return;state.answerLocked=true;submit.disabled=true;document.querySelectorAll(".word-button").forEach(button=>button.disabled=true);state.answers[p.id]=state.selectedAnswer;state.answerIndex++;askAnswer();};show("answer");}
function voteMarkup(){return state.words.map(w=>{const voters=state.players.filter((_,i)=>i!==state.order[state.parentIndex]).filter(p=>state.answers[p.id]===w).map(p=>p.name);return `<div class="vote-card ${w===state.parentWord?"parent-answer":""}"><div class="word">${esc(w)}</div><div class="vote-count">${voters.length}票</div><div class="voters">${voters.length?voters.map(esc).join("、"):"選択者なし"}</div></div>`;}).join("");}
function selectionMarkup(){return state.words.map(w=>{const voters=state.players.filter((_,i)=>i!==state.order[state.parentIndex]).filter(p=>state.answers[p.id]===w).map(p=>p.name);return `<div class="vote-card"><div class="word">${esc(w)}</div><div class="vote-count">${voters.length}票</div><div class="voters">${voters.length?voters.map(esc).join("、"):"選択者なし"}</div></div>`;}).join("");}
function showResultOpen(){document.querySelector("#result-open-card-area").innerHTML=cardMarkup(state.card);document.querySelector("#selection-summary").innerHTML=selectionMarkup();show("result-open");}
document.querySelector("#result-open-button").onclick=()=>{document.querySelector("#result-card-area").innerHTML=cardMarkup(state.card);document.querySelector("#result-votes").innerHTML=voteMarkup();const children=state.players.filter((_,i)=>i!==state.order[state.parentIndex]),correct=children.filter(p=>state.answers[p.id]===state.parentWord);document.querySelector("#result-summary").innerHTML=correct.length===0?"<strong>全員不正解</strong><span>親：+1ポイント</span>":correct.length===children.length?"<strong>全員正解</strong><span>子：全員+1ポイント<br>親：−1ポイント</span>":"<strong>一部の子が正解</strong><span>正解した子：各+1ポイント</span>";show("result");};
document.querySelector("#result-next").onclick=()=>{const children=state.players.filter((_,i)=>i!==state.order[state.parentIndex]),correct=children.filter(p=>state.answers[p.id]===state.parentWord),parent=state.players[state.order[state.parentIndex]];if(!correct.length)parent.score++;else if(correct.length===children.length){parent.score--;children.forEach(p=>p.score++);}else correct.forEach(p=>p.score++);document.querySelector("#score-summary").innerHTML=state.players.map(p=>`<div class="player-item"><span>${esc(p.name)}</span><span>${p.score}ポイント</span></div>`).join("");const winners=state.players.filter(p=>p.score>=5),nextRoundButton=document.querySelector("#next-round");document.querySelector("#score-title").textContent=winners.length?`勝利：${winners.map(p=>esc(p.name)).join("、")}`:(correct.length===0?"全員不正解":correct.length===children.length?"全員正解":"一部の子が正解");nextRoundButton.textContent=winners.length?"タイトルへ":"次のラウンドへ";nextRoundButton.dataset.action=winners.length?"title":"next-round";show("scores");};
function returnToTitle(){clearInterval(state.timer);Object.assign(state,{playerCount:0,cardSet:"vol1",players:[],order:[],parentIndex:0,card:null,official:[],words:[],parentWord:"",answers:{},answerIndex:0,answerLocked:false,selectedAnswer:"",timer:null,usedCards:new Set(),round:0,handoffNext:""});document.querySelectorAll("[data-card-set]").forEach(x=>x.classList.toggle("is-selected",x.dataset.cardSet==="vol1"));show("title");}
document.querySelector("#next-round").onclick=()=>{if(document.querySelector("#next-round").dataset.action==="title"){returnToTitle();return;}state.parentIndex=(state.parentIndex+1)%state.order.length;startRound();};
function stopGame(){clearInterval(state.timer);if(confirm("ゲームを終了してタイトル画面に戻りますか？\n現在のゲーム内容は失われます。")){location.reload();}}
["quit-button","public-quit","discussion-quit","score-quit"].forEach(id=>document.querySelector(`#${id}`).onclick=stopGame);
window.addEventListener("beforeunload",e=>{if(state.round){e.preventDefault();e.returnValue="";}});
history.pushState(null,"",location.href);window.addEventListener("popstate",()=>{history.pushState(null,"",location.href);stopGame();});
show("title");
